### ISSUE TITLE
Python 2.7 Compat

### ISSUE THREAD

**Issue by PeterMitrano** [darcamo/gdb_armadillo_helpers#4]
It seems like there was a PR to make this work in python2 by removing f-strings, but I think one was missed. in `gdb_std_complex_printer.py:29`

Just thought I'd point it out in case you would like to fix this, since it's just a 1-charecter change.

**Comment by darcamo** [comment]
That's true. The commit only changed `gdb_armadillo_printers.py`. I removed usage of f-strings in `gdb_std_complex_printer.py` and `gdb_armadillo_xmethods.py`.

Thanks
