### ISSUE TITLE
Add support for vscode and vscode-R

### ISSUE THREAD

**Issue by ilyaZar** [darcamo/gdb_armadillo_helpers#6]
Hi @darcamo thanks a lot for this great tool!

I wonder how to make use it inside vscode, do you have any experiences regarding this? 

Specifically, I eventually plan to use the pretty printing when debugging `C++` code that lives inside an `R` package. The standard tool for interfacing `R` and `C++` is `Rcpp` for which the strongest editor/debugger support currently comes in from of `vscode` (it already allows visual inspections similar to `CLion`); see  https://github.com/REditorSupport/vscode-R that is the vscode-extension.

I'd like to try that out and make it work, do you think:

1. it is possible directly? 
2. is there a lot to do to make this work? (I am willing to try and possibly PR here some changes along the way, if it is something relevant)

What do you think?

**Comment by darcamo** [comment]
I have no experience with R.

The pretty-printer code is not specific to vscode. As long as you source the pretty printer (e.g., add the relevant lines to your `.gdbinit` file) and the IDE/editor does nothing to get in the way of gdb loading your `.gdbinit` file, it should work just fine.

Here is a screenshot of the pretty-printer working in vscode with C++.
![image](https://github.com/darcamo/gdb_armadillo_helpers/assets/4071594/80f9850a-fb2f-4c35-b62a-6bb46d3bda9d)

If I comment-out the lines loading the pretty-printers in my `.gdbinit` file, this is what I get
![image](https://github.com/darcamo/gdb_armadillo_helpers/assets/4071594/c340c253-561a-483e-89af-571062659fa9)

**Comment by ilyaZar** [comment]
Hey @darcamo ! Sorry for the late reply  but now it's weekend :)

Thanks it works perfectly, I am getting the output from your screenshots above so it works perfectly with VS code!
